---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

author_note: >
  Complete departmental affiliations for each author (note the indentation, if you start a new paragraph).

  Enter author note here.

abstract: >
  Enter abstract here (note the indentation, if you start a new paragraph).
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
output            : papaja::apa6_word
---


<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r, cache = FALSE, include=FALSE}
library(knitr)
knitr::opts_knit$set(root.dir=normalizePath('../'))
```

```{r, echo=TRUE}
getwd()
```

```{r setup, echo=FALSE}
opts_chunk$set(echo = FALSE, cache=FALSE)
# connect to the file with the underlying R script  
read_chunk("./sandbox/Test_APA_document.R") 

```

```{r include = FALSE}
library("papaja")
```

<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load-packages}
```

```{r load-sources}
```

```{r load-data}
```

# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis

# Results

```{r descriptive-statistics, echo=FALSE, results='asis'}
```


```{r immediate-word-recall-model-summaries, echo=FALSE, results='asis'}
```


# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
